# Generated by Django 5.2.5 on 2025-09-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PHARMACIST', 'Pharmacist'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
