# Generated by Django 5.2.5 on 2025-09-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PHARMACIST', 'Pharmacist'), ('ADMIN', 'Administrator')], max_length=20),
        ),
    ]
