# Generated by Django 5.2.5 on 2025-08-27 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled')], default='PENDING', max_length=20)),
                ('diagnosis', models.TextField(blank=True, help_text='Medical diagnosis or condition')),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or comments')),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent prescription')),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('date_cancelled', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'PHARMACIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medicines.patient')),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Units prescribed')),
                ('dosage_instructions', models.TextField(blank=True, help_text='Specific dosage instructions')),
                ('duration', models.CharField(blank=True, help_text='e.g., 7 days, 2 weeks', max_length=100)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_medicines', to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicines', to='prescriptions.prescription')),
            ],
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_283c70_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescribed_by', 'date_issued'], name='prescriptio_prescri_8479ff_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'date_issued'], name='prescriptio_status_84f968_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionmedicine',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='min_prescribed_quantity'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionmedicine',
            unique_together={('prescription', 'medicine')},
        ),
    ]
