# Generated by Django 5.2.5 on 2025-08-27 18:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='medicines.medicine'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'last_name', 'date_of_birth')},
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(help_text='Primary supplier for this medicine', on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.supplier'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['medicine', 'timestamp'], name='medicines_i_medicin_09f583_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='medicines_i_perform_b246ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='non_negative_quantity'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__gt', datetime.date(2025, 8, 27))), name='valid_expiry_date'),
        ),
    ]
