# Generated by Django 5.2.5 on 2025-08-30 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicine',
            name='valid_expiry_date',
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__gt', datetime.date(2025, 8, 30))), name='valid_expiry_date'),
        ),
    ]
