# Generated by Django 5.2.5 on 2025-09-08 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_remove_medicine_valid_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicine',
            name='valid_expiry_date',
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__gt', datetime.date(2025, 9, 8))), name='valid_expiry_date'),
        ),
    ]
