# Generated by Django 5.2.5 on 2025-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRY_WARNING', 'Expiry Warning'), ('EXPIRED', 'Expired'), ('PRESCRIPTION_URGENT', 'Urgent Prescription'), ('PRESCRIPTION_PENDING', 'Pending Prescription'), ('STOCK_CRITICAL', 'Critical Stock'), ('SYSTEM', 'System Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('receive_low_stock_alerts', models.BooleanField(default=True)),
                ('receive_expiry_alerts', models.BooleanField(default=True)),
                ('receive_prescription_alerts', models.BooleanField(default=True)),
                ('receive_system_alerts', models.BooleanField(default=True)),
                ('min_severity_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('daily_digest', models.BooleanField(default=True)),
                ('immediate_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_notifications', models.BooleanField(default=True, help_text='Receive alerts via Telegram bot')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Personal Telegram chat ID for direct notifications', max_length=50)),
            ],
            options={
                'verbose_name': 'Alert Preference',
                'verbose_name_plural': 'Alert Preferences',
            },
        ),
    ]
